### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[2991, 7553, 2134, 9589], [2991, 7553, 2134, 7029], [2991, 3069, 2134, 6021], [3807, 9313, 6635, 1033, 3197], [3807, 9313, 6635, 1033, 5112], [6078, 2991, 5648, 2134, 3314], [2905, 3953, 4635, 1033]]


### Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2991 7553 2134 9589]
 [   0    0    0    0 2991 7553 2134 7029]
 [   0    0    0    0 2991 3069 2134 6021]
 [   0    0    0 3807 9313 6635 1033 3197]
 [   0    0    0 3807 9313 6635 1033 5112]
 [   0    0    0 6078 2991 5648 2134 3314]
 [   0    0    0    0 2905 3953 4635 1033]]


In [10]:
dim=10


In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

c:\Users\gaura\miniconda3\envs\ai\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step
[[[-0.03698075 -0.02247869 -0.00223867 -0.00841862 -0.01257795
    0.01765377  0.01626274 -0.02745807 -0.00436008  0.02269996]
  [-0.03698075 -0.02247869 -0.00223867 -0.00841862 -0.01257795
    0.01765377  0.01626274 -0.02745807 -0.00436008  0.02269996]
  [-0.03698075 -0.02247869 -0.00223867 -0.00841862 -0.01257795
    0.01765377  0.01626274 -0.02745807 -0.00436008  0.02269996]
  [-0.03698075 -0.02247869 -0.00223867 -0.00841862 -0.01257795
    0.01765377  0.01626274 -0.02745807 -0.00436008  0.02269996]
  [-0.0114979   0.01841224  0.04631332  0.03531087 -0.04619613
   -0.04671372 -0.02015113 -0.04815647 -0.01833938 -0.00600834]
  [-0.029062    0.02686653  0.01718007 -0.00340017  0.00430971
    0.01344601  0.04604894  0.03873732 -0.04317652 -0.02873396]
  [-0.01142442  0.03952226  0.04396028  0.01133157  0.03791166
    0.03346321  0.00566227 -0.04650782 -0.04448264  0.00407817]
  [-0.03628105  0.01519997 -0.02043893 -0.01140672 -0.00869592
   -0.035

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2991, 7553, 2134, 9589], dtype=int32)

In [15]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[-0.03698075 -0.02247869 -0.00223867 -0.00841862 -0.01257795  0.01765377
   0.01626274 -0.02745807 -0.00436008  0.02269996]
 [-0.03698075 -0.02247869 -0.00223867 -0.00841862 -0.01257795  0.01765377
   0.01626274 -0.02745807 -0.00436008  0.02269996]
 [-0.03698075 -0.02247869 -0.00223867 -0.00841862 -0.01257795  0.01765377
   0.01626274 -0.02745807 -0.00436008  0.02269996]
 [-0.03698075 -0.02247869 -0.00223867 -0.00841862 -0.01257795  0.01765377
   0.01626274 -0.02745807 -0.00436008  0.02269996]
 [-0.0114979   0.01841224  0.04631332  0.03531087 -0.04619613 -0.04671372
  -0.02015113 -0.04815647 -0.01833938 -0.00600834]
 [-0.029062    0.02686653  0.01718007 -0.00340017  0.00430971  0.01344601
   0.04604894  0.03873732 -0.04317652 -0.02873396]
 [-0.01142442  0.03952226  0.04396028  0.01133157  0.03791166  0.03346321
   0.00566227 -0.04650782 -0.04448264  0.00407817]
 [-0.03628105  0.01519997 -0.02043893 -0.01140672 -0.00869592 -0.03532969
  -0.01765277